name: Realse & Upgrade


on:
  release:
    types: [published]

jobs:

  build:
  
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build & push container
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/scai-bio/helm-upgrade-actions/hello-world:${{ github.event.release.tag_name }}

  deploy:

    name: Update k8s deployment
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: helm-deploy
      uses: WyriHaximus/github-action-helm3@v2.0
      with:
        exec: helm upgrade hello-world helm --namespace=bio --set=ui.version=${{ github.event.release.tag_name }}
        kubeconfig: '${{ secrets.KUBECONFIG }}'
